# Generated by Django 4.2.4 on 2023-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.CharField(max_length=150)),
                ('reseña', models.CharField(max_length=150)),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('temporada', models.TextField()),
                ('descripcion', models.CharField(max_length=150)),
                ('reseña', models.CharField(max_length=150)),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
