# Generated by Django 4.2.4 on 2023-10-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0007_alter_pelicula_descripcion_alter_pelicula_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Peliculas/'),
        ),
    ]
