# Generated by Django 4.2.4 on 2023-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0018_rename_imagen_pelicula_imagenpelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagenpelicula',
            field=models.ImageField(blank=True, null=True, upload_to='media\\pelicula'),
        ),
    ]
