# Generated by Django 4.2.5 on 2023-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0020_alter_pelicula_imagenpelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagenpelicula',
            field=models.ImageField(blank=True, null=True, upload_to='pelicula/%Y/%m/%d'),
        ),
    ]
