# Generated by Django 4.2.4 on 2023-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0026_alter_pelicula_imagenpelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='imagen',
        ),
        migrations.AddField(
            model_name='serie',
            name='imagenserie',
            field=models.ImageField(blank=True, null=True, upload_to='pelicula/'),
        ),
    ]
