# Generated by Django 4.2.4 on 2023-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0027_remove_serie_imagen_serie_imagenserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='descripcion',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='serie',
            name='reseña',
            field=models.CharField(max_length=600),
        ),
    ]
